workflows:
  default:
    name: Build Flutter IronMind APK
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: 3.19.6   # <-- versiune stabilă care merge cu setup-ul tău
      xcode: 15.0       # (opțional, dar bun pentru iOS)

    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
