workflows:
  default:
    name: Build Flutter IronMind APK
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Navigate to project root
        script: cd flutter-ironmind-main
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
